version: '3.7'
services:
  postgresql:
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
      args:
        - POSTGRESQL_VERSION=$POSTGRESQL_VERSION
    image: postgresql-shm:5.7.32
    container_name: postgresql-shm
    hostname: postgresql
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_HOST_AUTH_METHOD=$POSTGRES_HOST_AUTH_METHOD
      - COMPOSE_HTTP_TIMEOUT=120
    ports:
      - "3307:3306"
    volumes:
      - $PWD/container_data/postgresql:/var/lib/postgresql/
      - $PWD/docker/postgres/init:/docker-entrypoint-initdb.d
    cap_add: 
      - SYS_NICE # CAP_SYS_NICE

  mlflow:
    build:
      context: ./docker/mlflow
      dockerfile: Dockerfile
      args:
        - MLFLOW_ARTIFACT_DIR=$MLFLOW_ARTIFACT_DIR
        - MLFLOW_TRACKING_URI=$MLFLOW_TRACKING_URI
    container_name: mlflow-tracking_postgres
    image: mlflow-tracking:1.12.1
    hostname: mlflow-tracking
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - MLFLOW_ARTIFACT_URI=${MLFLOW_ARTIFACT_DIR}
      - MLFLOW_TRACKING_URI=${MLFLOW_TRACKING_URI}
    depends_on:
      - postgresql
    links:
      - "postgresql:postgresql"
    ports:
      - "5000:5000"
    volumes:
      - /home/ctolon:/mnt/mlruns


