version: '3'
services:
  sftp:
    image: atmoz/sftp:alpine
    container_name: sftp
    restart: always
    expose:
      - "${SFTP_PORT}"
    ports:
      - "2222:22"
    command:
      - ${SFTP_USERNAME}:${SFTP_PASSWORD}:1001:1:${MLFLOW_ARTIFACT_STORE}   # syntax: user:password[:e][:uid[:gid[:dir1[,dir2]...]]]
    volumes:
      - ./${MLFLOW_ARTIFACT_STORE}:/home/${SFTP_USERNAME}/${MLFLOW_ARTIFACT_STORE}
      - ./keys/ssh_host_rsa_key.pub:/home/${SFTP_USERNAME}/.ssh/ssh_host_rsa_key.pub:ro
      - ./keys/ssh_host_ed25519_key.pub:/home/${SFTP_USERNAME}/.ssh/ssh_host_ed25519_key.pub:ro
      #- ./keys/ssh_host_ecdsa_key.pub:/home/${SFTP_USERNAME}/.ssh/ssh_host_ecdsa_key.pub:ro
      - ./sshd_config:/etc/ssh/sshd_config
      #- ${SFTP_ED25519_KEY:-/etc/ssh/ssh_host_ed25519_key}:/etc/ssh/ssh_host_ed25519_key:ro
      #- ${SFTP_RSA_KEY:-/etc/ssh/ssh_host_rsa_key}:/etc/ssh/ssh_host_rsa_key:ro
      #- ${SFTP_ECDSA_KEY:-/etc/ssh/ssh_host_ecdsa_key}:/etc/ssh/ssh_host_ecdsa_key:ro

  postgresql:
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
      args:
        - POSTGRESQL_VERSION=$POSTGRESQL_VERSION
    image: postgresql-shm:5.7.32
    container_name: postgresql-shm
    hostname: postgresql
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      #- POSTGRES_HOST_AUTH_METHOD=$POSTGRES_HOST_AUTH_METHOD
      - COMPOSE_HTTP_TIMEOUT=120
    ports:
      - "3307:3306"
    volumes:
      - $PWD/container_data/postgresql:/var/lib/postgresql
      - $PWD/docker/postgres/init:/docker-entrypoint-initdb.d
    cap_add: 
      - SYS_NICE # CAP_SYS_NICE

  mlflow:
    build:
      context: ./docker/mlflow
      dockerfile: Dockerfile
      args:
        - MLFLOW_ARTIFACT_DIR=$MLFLOW_ARTIFACT_DIR
        - MLFLOW_TRACKING_URI=$MLFLOW_TRACKING_URI
    container_name: mlflow-tracking_postgres
    image: mlflow-tracking:1.12.1
    hostname: mlflow-tracking
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - WAIT_FOR_IT_TIMEOUT=${WAIT_FOR_IT_TIMEOUT}
      - MLFLOW_ARTIFACT_URI=${MLFLOW_ARTIFACT_DIR}
      - MLFLOW_TRACKING_URI=${MLFLOW_TRACKING_URI}
      - SFTP_USERNAME=${SFTP_USERNAME}
      - SFTP_PASSWORD=${SFTP_PASSWORD}
      - SFTP_HOST=${SFTP_HOST}
    depends_on:
      - postgresql
      - sftp
    links:
      - "postgresql:postgresql"
      - "sftp:sftp"
    ports:
      - "5000:5000"
    volumes:
      - ./${MLFLOW_ARTIFACT_STORE}:/${MLFLOW_ARTIFACT_STORE}
      - ./keys/ssh_host_rsa_key:/root/.ssh/ssh_host_rsa_key:ro
      - ./keys/ssh_host_ed25519_key:/root/.ssh/ssh_host_ed25519_key:ro
      #- ./keys/ssh_host_ecdsa_key:/root/.ssh/ssh_host_ecdsa_key:ro   config dosyası bir aşağıdaki satırda 
      - ./keys/config:/root/.ssh/config:ro
    command: >
      /bin/bash -c "sleep 3
      && cd /root/.ssh
      && ssh-keyscan ${SFTP_HOST} >> known_hosts
      && cd /server
      && mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri postgresql+psycopg2://postgres:mysecret@postgresql/mlflow --default-artifact-root sftp://mlflowuser:secret@0.0.0.0/home/mlflowuser/artifacts"
